services:
  db:
    image: postgres:15-alpine
    container_name: ticket_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticketdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./ticketing-backend
      dockerfile: Dockerfile
    container_name: ticket_be
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/ticketdb?schema=public
      - PORT=8080
      - NODE_ENV=production
      - CORS_ORIGIN=*
      - JWT_SECRET=e11f4bac12e43465f548b58f1e5e5683e84b1b298354615b7cde0534a154458561aa86d6e07c0c869a58fe16009e4198
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma db push && npm start"

  frontend:
    build:
      context: ./ticketing-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
    container_name: ticket_fe
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: